import RAW from '../../scripts/voice/commander_lines.txt?raw';

/**
 * The Warden's voice (SABLE commander), generated by scripts/gen-commander-voice.mjs.
 * One sound event per line ('bd.cmd.commander_threat_03') so the subtitle always
 * matches what is said; the performance tags ([sniffs], [echoing] ...) are stripped
 * from the subtitle.
 */
export type CommanderCategory =
  | 'firstcontact' | 'threat' | 'search' | 'lost' | 'command' | 'allydown' | 'personal'
  | 'hit' | 'lowhp' | 'reload' | 'retreat' | 'close' | 'neardeath' | 'kill' | 'rare';

/** Categories whose audio exists in public/audio/voice. Add the rest once they are generated. */
const READY = new Set<CommanderCategory>(['firstcontact', 'threat', 'search', 'lost', 'command', 'allydown', 'personal', 'hit', 'lowhp', 'reload', 'retreat', 'close']);

export interface CommanderLine {
  id: string;
  text: string;
}

const BY_CATEGORY = new Map<CommanderCategory, CommanderLine[]>();
for (const raw of RAW.split(/\r?\n/)) {
  const i = raw.indexOf('|');
  if (i < 0) continue;
  const id = raw.slice(0, i).trim();
  const cat = id.split('_')[1] as CommanderCategory;
  if (!READY.has(cat)) continue;
  const text = raw.slice(i + 1).replace(/\[[^\]]*\]/g, '').replace(/\s+/g, ' ').trim();
  const list = BY_CATEGORY.get(cat) ?? [];
  list.push({ id, text });
  BY_CATEGORY.set(cat, list);
}

export const COMMANDER_LINES: readonly CommanderLine[] = [...BY_CATEGORY.values()].flat();

const lastPick = new Map<CommanderCategory, string>();

/** A random line of the category (never the same one twice in a row), or null if it has no audio yet. */
export function pickCommanderLine(cat: CommanderCategory): CommanderLine | null {
  const list = BY_CATEGORY.get(cat);
  if (!list?.length) return null;
  let line = list[(Math.random() * list.length) | 0];
  if (line.id === lastPick.get(cat) && list.length > 1) line = list[(list.indexOf(line) + 1) % list.length];
  lastPick.set(cat, line.id);
  return line;
}
